import type {Metadata} from 'next'
import Image from 'next/image'
import Link from 'next/link'
import {RelationshipHero} from '@/components/relationship-hero'
import {RelationshipMotion} from '@/components/relationship-motion'
import {partnerTypes,partnerFaqs,partnerNext,partnerStack,partnerOfferChecks} from '@/content/partners'
export const metadata:Metadata={title:'Partner with Tadiran',description:'Grow your communications business with Tadiran technology, regional support and your local expertise.',alternates:{canonical:'/partners'}}
const modelImages=['cloud-infrastructure','mso','integrations-deployment','oem']
export default function Partners(){return <RelationshipMotion className="page partner-page relationship-page">
 <RelationshipHero kind="partners"/>
 <section className="partner-principles relationship-shell" data-stagger>{[['01','Your customer relationships','Keep the local knowledge, service and accountability that make your business valuable.'],['02','A platform to build on','Bring Aeonix communications and customer experience into the services you already deliver.'],['03','People in your corner','Connect with regional teams for product expertise, enablement and ongoing collaboration.']].map(([n,title,body])=><article key={n}><small>{n}</small><h2>{title}</h2><p>{body}</p></article>)}</section>
 <section className="partnership-offer" id="offer"><div className="relationship-shell partnership-offer__grid"><div className="partnership-offer__visual" data-photo><Image src="/brand/cinema/sections/aeonix.png" alt="Enterprise colleagues working together" fill sizes="(max-width:760px) 100vw,50vw"/><div className="partnership-device"><Image src="/brand/reference-assets/aeonix-mobile.webp" alt="Aeonix Touch application" width={660} height={1200}/></div></div><div className="partnership-offer__copy"><p className="cine-eyebrow">Aeonix4Cloud / Partner program</p><h2>Your next chapter.<br/><em>Built together.</em></h2><p>Bring enterprise communications to your customers with a platform you can position, deliver and support.</p><ul>{partnerOfferChecks.map(s=><li key={s}>{s}</li>)}</ul><Link className="cine-button" href="/partners/apply">Explore the opportunity ↗</Link></div></div></section>
 <section className="relationship-shell partner-models" id="types"><div className="relationship-section-head"><div><p className="cine-eyebrow">Find your place</p><h2>Different strengths.<br/><em>A shared opportunity.</em></h2></div><p>Choose the partnership that fits the way you work and the customers you serve.</p></div><div className="partner-models__grid" data-stagger>{partnerTypes.map((type,i)=><Link className="partner-model" href={`/partners/apply?type=${encodeURIComponent(type.name)}`} id={type.id} key={type.id}><div className="partner-model__photo"><Image src={`/brand/cinema/sections/${modelImages[i]}.png`} alt="" fill sizes="(max-width:760px) 100vw,50vw"/></div><div className="partner-model__copy"><small>0{i+1}</small><h3>{type.name}<span>↗</span></h3><p>{type.body}</p><span>Explore this partnership</span></div></Link>)}</div></section>
 <section className="partner-enablement" id="enablement"><div className="relationship-shell"><div className="relationship-section-head"><div><p className="cine-eyebrow">What’s behind the partnership</p><h2>The support to<br/><em>move forward.</em></h2></div><p>Product capability, commercial opportunity and practical enablement, brought together.</p></div><div className="partner-enablement__grid" data-stagger>{partnerStack.map((s,i)=><article key={s.title}><small>0{i+1}</small><h3>{s.title}</h3><p>{s.body}</p></article>)}</div></div></section>
 <section className="relationship-shell partner-next" id="next"><p className="cine-eyebrow">From introduction to partnership</p><h2>A clear path forward.</h2><ol data-stagger>{partnerNext.map((s,i)=><li key={s.label}><span>0{i+1}</span><h3>{s.label}</h3><p>{s.body}</p></li>)}</ol></section>
 <section className="relationship-shell partner-questions" id="faq"><div><p className="cine-eyebrow">A few useful answers</p><h2>Before we begin.</h2><Link className="cine-text-link" href="/contact?intent=partnerships">Ask our partner team ↗</Link></div><div className="faq-list">{partnerFaqs.map(f=><details key={f.question}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></section>
 <section className="relationship-closing"><p className="cine-eyebrow">Your market. Our shared future.</p><h2>Let’s grow something together.</h2><Link className="cine-button" href="/partners/apply">Become a partner ↗</Link></section>
 </RelationshipMotion>}
