export type DetailDirection = {
 title:string; lead:string; layout:'workspace'|'device'|'portrait'|'editorial'|'panorama'|'dark'|'reverse';
 chapter:string; introduction:string; mode:'channels'|'network'|'voice'|'review'|'insight'|'mobility'|'resilience'|'deployment'|'cloud'|'oem'|'mso';
 steps:[string,string][]; closing:string;
}
export const productFeatures:Record<string,{title:string;body:string}[]>={
 omnicx:[{title:'Every channel in context',body:'Bring voice, WhatsApp, live chat and email into one customer conversation.'},{title:'An empowered service team',body:'Connect agent guidance, customer context and supervisor visibility with daily work.'},{title:'A connected operation',body:'Bring CRM, telephony and business systems into the service workflow.'}],
 aeonix:[{title:'Connected teams',body:'Bring voice, video, mobility and collaboration into one communications foundation.'},{title:'Operational control',body:'Connect consoles, call routing, dispatch and recording to the way teams work.'},{title:'Continuity and choice',body:'Plan high availability and recovery with cloud, hybrid or on-premises deployment.'}],
 'mobile-touch':[{title:'Voice and video',body:'Keep mobile colleagues part of the conversation wherever their work takes them.'},{title:'People within reach',body:'Connect organizational chat and mobile contacts with everyday communication.'},{title:'A connected working day',body:'Bring mobile and desktop communications together for teams moving between locations.'}],
 ava:[{title:'A defined service role',body:'Focus assistance on a clear request, routing step or agent support task.'},{title:'A thoughtful handoff',body:'Plan when to involve a person and what information should accompany the conversation.'},{title:'A considered introduction',body:'Review available capabilities and environment fit with the team before defining the service.'}],
 'recording-quality':[{title:'Capture with purpose',body:'Plan recording around the conversations and records your organization needs.'},{title:'Review with context',body:'Connect interaction records with evaluation and supervisor review.'},{title:'Coach for the next conversation',body:'Use quality observations to support people and improve service practices.'}],
 analytics:[{title:'Operational reporting',body:'Bring the questions and measures that matter to service leaders into focus.'},{title:'Quality insight',body:'Connect interaction information with coaching and process review.'},{title:'The right view for the role',body:'Plan who needs the information and how it will support their decisions.'}],
}
export const productDirections:Record<string,DetailDirection>={
 omnicx:{title:'One workspace.\nEvery conversation.',lead:'Connect voice, digital channels, customer context and your people. Help agents work smarter and supervisors stay in control.',layout:'workspace',chapter:'The channel changes.\nThe conversation continues.',introduction:'Voice, WhatsApp, live chat and email belong in the same service journey. OmniCX brings them into one managed flow, with the context teams need to respond.',mode:'channels',steps:[['Connect','Bring voice and digital interactions into one environment.'],['Empower','Give agents the customer context and guidance to help.'],['Deliver','Keep supervisors close to queues, quality and workload.']],closing:'Make your next conversation a better one.'},
 aeonix:{title:'Your people.\nWithin reach.',lead:'Enterprise communications for offices, mobile teams and control rooms. Bring voice, video and mobility together on a foundation built for continuity.',layout:'device',chapter:'One foundation.\nMany ways to connect.',introduction:'Business telephony is only the beginning. Connect everyday collaboration with the consoles, routing and recording that support your operation.',mode:'network',steps:[['Office','Keep business calls, reception and collaboration connected.'],['Field','Extend the conversation to people away from their desks.'],['Operations','Connect control rooms with the teams they coordinate.']],closing:'Build your communications foundation.'},
 'mobile-touch':{title:'The office number.\nWithout the office.',lead:'Keep people connected as work moves between desks, sites and the field. Bring enterprise communications into the hands of your teams.',layout:'portrait',chapter:'Work moves.\nThe conversation follows.',introduction:'From a hotel service request to a colleague across campus, mobile communications help the right person stay within reach.',mode:'mobility',steps:[['Stay reachable','Carry the enterprise conversation between locations.'],['Find your people','Keep mobile contacts and organizational chat close.'],['Work together','Connect by voice or video while on the move.']],closing:'Keep your mobile teams connected.'},
 ava:{title:'A little assistance.\nA more human service.',lead:'Explore voice assistance that supports your service team, from understanding a request to helping it reach the right person.',layout:'reverse',chapter:'Listen. Understand.\nBring the right person in.',introduction:'Start with a clear service task. Define how assistance supports it, when a person takes over and what context should travel with the handoff.',mode:'voice',steps:[['Listen','Start with the customer’s request and the service they need.'],['Assist','Explore routing and prompts within a defined workflow.'],['Connect','Keep a clear route to a person when the conversation needs one.']],closing:'Find the right place for assistance.'},
 'recording-quality':{title:'Every conversation\ncan teach you something.',lead:'Bring interaction recording, evaluation and coaching into a considered quality workflow. Help people learn from the conversations that matter.',layout:'editorial',chapter:'From a recorded call\nto a better next conversation.',introduction:'A useful quality program connects what happened with what your team can learn. Plan capture, reviewer access and coaching together.',mode:'review',steps:[['Capture','Define the conversations and records your operation needs.'],['Review','Give authorized reviewers a purposeful evaluation process.'],['Coach','Turn observations into practical guidance for the team.']],closing:'Put quality at the heart of service.'},
 analytics:{title:'See the story\nbehind the conversation.',lead:'Turn interaction data into a clearer view of service. Give supervisors and operations leaders a useful starting point for their next decision.',layout:'panorama',chapter:'A clearer picture.\nA more useful next step.',introduction:'Look beyond the export. Connect reporting with the people, questions and operational decisions it is meant to support.',mode:'insight',steps:[['Observe','Bring the measures that matter into view.'],['Understand','Explore patterns across workload, interactions and quality.'],['Improve','Use the picture to guide coaching and operational changes.']],closing:'Make insight part of everyday work.'},
}
export const solutionDirections:Record<string,DetailDirection>={
 'enterprise-communications':{title:'Bring your whole\norganization closer.',lead:'Connect offices, mobile teams and control rooms with communications built around the way your organization works.',layout:'panorama',chapter:'From the front desk\nto the field.',introduction:'People should be able to reach one another across locations and roles. Bring business telephony, collaboration and mobility into one communications plan.',mode:'network',steps:[['Office teams','Reception, calls and everyday collaboration.'],['Mobile colleagues','Campus, site and field communications.'],['Control rooms','Dispatch, priority calling and coordination.']],closing:'Connect the people behind your business.'},
 'omnichannel-cx':{title:'Start anywhere.\nContinue everywhere.',lead:'Your customers move between channels. Help your teams continue the conversation with customer context, routing and service tools together.',layout:'reverse',chapter:'From customer demand\nto service delivery.',introduction:'Connect the customer journey with the teams delivering it. Build a service environment around agents, supervisors and the work they do every day.',mode:'channels',steps:[['Customer demand','Voice, WhatsApp, live chat and email.'],['Connected service','Routing, unified context and integrations.'],['Team delivery','Agents, supervisors and quality workflows.']],closing:'Create a more connected customer experience.'},
 'ai-analytics':{title:'Intelligence with\na purpose.',lead:'Bring assistance and insight into the service moments where they can help people work better.',layout:'editorial',chapter:'Support the conversation.\nLearn from the interaction.',introduction:'AI and analytics play different roles. One can support the task in front of an agent; the other helps leaders understand the wider operation.',mode:'insight',steps:[['During service','Explore routing, prompts and agent assistance.'],['After the interaction','Connect summaries, recording and quality review.'],['Across the operation','Use reporting to inform coaching and improvement.']],closing:'Start with the workflow you want to improve.'},
 'critical-communications':{title:'When every\nconnection matters.',lead:'Keep control rooms, field teams and essential sites connected through priority calling, dispatch and recording.',layout:'dark',chapter:'Coordinate the response.\nKeep the operation moving.',introduction:'In transport, utilities and care environments, communications support the people responsible for essential services. Plan around their real operational workflows.',mode:'network',steps:[['Control','Bring requests and operational information into the control room.'],['Coordinate','Reach the team responsible for the next action.'],['Respond','Keep the field and control room connected through the response.']],closing:'Let’s talk about your critical operation.'},
 'security-resilience':{title:'Continuity,\nby design.',lead:'Bring resilience, access and operational visibility into the architecture of your communications.',layout:'device',chapter:'Plan for more than\nthe everyday.',introduction:'Understand what must keep working, who needs access and how your teams will respond when conditions change.',mode:'resilience',steps:[['Availability','Map essential services and dependencies.'],['Control','Define access, ownership and administrative responsibilities.'],['Recovery','Plan failover and recovery around operational priorities.']],closing:'Design around the continuity you need.'},
 'integrations-deployment':{title:'Build on what works.\nConnect what’s next.',lead:'Bring your communications and business systems together, with a deployment path that respects the infrastructure you already have.',layout:'reverse',chapter:'Your systems stay\nin the conversation.',introduction:'CRM, property management, operational systems and communications should work together. Start with the handoffs that matter to your organization.',mode:'deployment',steps:[['Discover','Map systems, sites and the workflows between them.'],['Connect','Define integrations and responsibilities.'],['Transition','Plan rollout, handover and ongoing support.']],closing:'Map your next step with us.'},
 'cloud-infrastructure':{title:'Room to grow.\nBuilt around you.',lead:'Plan cloud communications around your sites, connectivity and operational needs. Create a path that can evolve with your organization.',layout:'panorama',chapter:'The service is only\npart of the story.',introduction:'Connectivity, responsibilities and local requirements shape a successful cloud approach. Bring them into the plan from the beginning.',mode:'cloud',steps:[['Your sites','Understand users, locations and network dependencies.'],['Your service','Define the communications environment and support ownership.'],['Your next chapter','Plan how new sites and hybrid requirements fit.']],closing:'Shape your cloud communications plan.'},
 oem:{title:'Your product.\nMore connected.',lead:'Explore a communications layer for the products and services you already bring to market.',layout:'editorial',chapter:'Build on a foundation.\nMake the experience yours.',introduction:'Connect product ambition with integration expertise. Work through platform fit, branding and engineering responsibilities with the Tadiran partner team.',mode:'oem',steps:[['Your experience','Define the customer workflow and the product you want to build.'],['Communications layer','Explore platform extension, APIs and integration scope.'],['Delivery together','Agree engineering ownership and deployment packaging.']],closing:'Let’s explore what you’re building.'},
 mso:{title:'Your market.\nMore possibilities.',lead:'Bring communications and customer experience into the relationships you already own, backed by regional teams and a global partner ecosystem.',layout:'reverse',chapter:'Local relationships.\nA broader offering.',introduction:'Build from your market knowledge. Shape an offering that connects customer needs with the right communications technology and delivery support.',mode:'mso',steps:[['Understand','Identify the customers and needs you know best.'],['Shape','Build the offering around communications and CX.'],['Deliver','Plan enablement, coverage and ongoing customer support.']],closing:'Grow your next opportunity with Tadiran.'},
}
