import Image from 'next/image'
import Link from 'next/link'
import {CinemaStage} from './cinema-stage'
import {Reveal} from './reveal'
import {FeatureMotion} from './feature-motion'
import {brandFacts} from '@/content/brand-story'
export function CinemaHome(){return <div className="cinema-home"><CinemaStage/>
 <section className="cine-manifesto cine-wrap" id="possibilities"><Reveal><p className="cine-eyebrow">Built for the moments that matter</p><h2>Technology should bring us<br/><em>closer together.</em></h2><div className="cine-manifesto-bottom"><p>To your customers. To your colleagues. To what comes next.<br/>Tadiran connects the conversations and systems that keep your business moving.</p><Link className="cine-text-link" href="/about">Meet Tadiran ↗</Link></div></Reveal><div className="cine-facts">{brandFacts.map(f=><div key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div><small className="cine-source">Company profile · September 2026</small></section>
 <section className="cine-product cine-product-cx"><div className="cine-wrap"><Reveal><p className="cine-eyebrow">01 / Customer experience</p><div className="cine-product-heading"><h2>Many channels.<br/><em>One human experience.</em></h2><div><p>Give every conversation the context it deserves. Bring your channels and teams together with OmniCX.</p><Link className="cine-button" href="/products/omnicx">Explore OmniCX ↗</Link></div></div></Reveal><FeatureMotion className="cine-product-composition"><div className="cine-product-photo"><Image className="cine-product-human" src="/brand/cinema/sections/home-cx.png" alt="Service agent helping a customer" fill sizes="(max-width:760px) 100vw,42vw"/></div><div className="cine-ui-window"><div><span/><span/><span/><b>OmniCX / Your connected workspace</b></div><Image src="/brand/reference-assets/omnicx-workspace.webp" alt="Actual OmniCX agent workspace" width={1500} height={844}/></div><div className="cine-caption"><span>Voice. Digital. Context.</span><strong>Keep the conversation going.</strong></div></FeatureMotion></div></section>
 <section className="cine-product cine-wrap"><Reveal><p className="cine-eyebrow">02 / Enterprise communications</p><div className="cine-product-heading"><h2>Work happens everywhere.<br/><em>Be there, together.</em></h2><div><p>Connect offices, mobile teams and critical operations. Aeonix keeps your people within reach.</p><Link className="cine-button" href="/products/aeonix">Explore Aeonix ↗</Link></div></div></Reveal><FeatureMotion className="cine-enterprise-composition"><div className="cine-enterprise-photo"><Image src="/brand/cinema/sections/home-uc.png" alt="A project manager coordinating by phone" fill sizes="(max-width:760px) 100vw,58vw"/></div><div className="cine-mobile-device"><Image src="/brand/reference-assets/aeonix-mobile.webp" alt="Aeonix Touch mobile application" width={660} height={1200}/></div><div className="cine-enterprise-label"><small>From a single call to your entire organization.</small><strong>Always a connection<br/>worth making.</strong></div></FeatureMotion></section>
 <section className="cine-choice"><div className="cine-wrap"><p className="cine-eyebrow">Your path to what’s next</p><div className="cine-product-heading"><h2>Move forward.<br/><em>On your terms.</em></h2><p>Cloud, hybrid or on premises. Shape your communications around your organization, with the flexibility to evolve.</p></div><div className="cine-choice-row">{[['Cloud','Connect distributed teams.'],['Hybrid','Bridge existing and new.'],['On premises','Keep control close.']].map(([title,body],i)=><Link href="/solutions/integrations-deployment" key={title}><small>0{i+1}</small><h3>{title}<span>↗</span></h3><p>{body}</p></Link>)}</div></div></section>
 <section className="cine-world cine-wrap"><Reveal><p className="cine-eyebrow">Built around your world</p><h2>A connection can<br/><em>change someone’s day.</em></h2></Reveal><FeatureMotion className="cine-world-feature"><Image src="/brand/cinema/sections/home-hospitality.png" alt="A warm welcome at a hotel reception" fill sizes="100vw"/><div><span>Hospitality / SmartHotel</span><h3>Behind every great stay,<br/>a connected team.</h3><Link className="cine-button cine-button-white" href="/industries/hospitality">Explore hospitality ↗</Link></div></FeatureMotion><div className="cine-industry-links">{[['Healthcare','healthcare'],['Transportation','transportation'],['Power & Utilities','power-utilities'],['Education','education']].map(([title,slug])=><Link key={slug} href={`/industries/${slug}`}>{title}<span>↗</span></Link>)}</div><Link className="cine-text-link" href="/industries">Explore every industry ↗</Link></section>
 <section className="cine-partner"><div className="cine-wrap"><p className="cine-eyebrow">Global technology. Local relationships.</p><h2>Good things happen<br/><em>when we connect.</em></h2><p>Bring Tadiran to your market. Build on local expertise, regional support and a shared commitment to your customers.</p><div className="cine-actions"><Link className="cine-button" href="/partners">Become a partner ↗</Link><Link className="cine-text-link" href="/resources">Explore resources ↗</Link></div></div></section>
 </div>}
