import Image from 'next/image'
import Link from 'next/link'
import {ArrowRight,Phone,MessageCircle,Mail,Headphones,Check,Layers,ShieldCheck,Radio,Server,Building2,Users} from 'lucide-react'
import {campaignImage} from '@/content/campaign-images'
import {productDirections,solutionDirections,productFeatures,type DetailDirection} from '@/content/detail-directions'
import {findByHref,type Product,type Solution} from '@/content/portfolio'
import {OfferingMotion} from './offering-motion'
import {DetailSignal,DeploymentExplorer} from './detail-signal'
import {ProductComposition} from './product-composition'

const icons=[Phone,MessageCircle,Mail,Headphones]
function Lines({text}:{text:string}){return <>{text.split('\n').map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</>}
function Photo({slug,className=''}:{slug:string;className?:string}){const p=campaignImage(slug)!;return <div className={`offering-photo ${className}`} data-photo><Image src={p.src} alt={p.alt} fill sizes="(max-width:760px) 100vw,60vw" style={{objectPosition:p.position}}/></div>}
function StepCards({d}:{d:DetailDirection}){return <ol className="offering-steps" data-stagger>{d.steps.map(([title,body],i)=><li key={title}><small>0{i+1}</small><h3>{title}</h3><p>{body}</p></li>)}</ol>}
function Channels(){return <div className="offering-channels" data-stagger>{['Voice','WhatsApp & chat','Email','Agent workspace'].map((label,i)=>{const Icon=icons[i];return <div key={label}><Icon size={24}/><span>{label}</span>{i<3&&<ArrowRight size={16}/>}</div>})}</div>}
function Caption({children}:{children:React.ReactNode}){return <p className="offering-caption">{children}</p>}

function ProductStory({item,d}:{item:Product;d:DetailDirection}){
 if(item.slug==='omnicx')return <>
  <section className="offering-chapter offering-shell"><div className="offering-heading"><div><p className="cine-eyebrow">Connect / Empower / Deliver</p><h2><Lines text={d.chapter}/></h2></div><p>{d.introduction}</p></div><Channels/><StepCards d={d}/></section>
  <section className="offering-bpo"><div className="offering-shell offering-bpo__grid"><Photo slug="omnicx"/><div><p className="cine-eyebrow">Built for BPO operations</p><h2>More context for agents.<br/>More visibility for leaders.</h2><p>Support shared services, outsourced support and multi-client service environments with one connected working model.</p><ul>{['Omnichannel routing','Unified agent workspace','AI assistance','Supervisor visibility','Workflow automation','Open integrations'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><Link className="offering-link" href="/solutions/omnichannel-cx">Explore the customer experience solution <ArrowRight size={17}/></Link></div></div></section>
 </>
 if(item.slug==='aeonix')return <><section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><DetailSignal kind="network" steps={d.steps}/></section><section className="offering-places offering-shell"><p className="cine-eyebrow">One platform, different responsibilities</p><div className="offering-places__grid">{[['healthcare','The people behind care','Connect staff across facilities and mobile teams.'],['transportation','The people behind every journey','Bring control rooms, dispatch and field teams closer.']].map(([slug,title,body])=><Link href={`/industries/${slug}`} key={slug}><Photo slug={slug}/><h3>{title}</h3><p>{body}</p><ArrowRight size={20}/></Link>)}</div></section></>
 if(item.slug==='mobile-touch')return <><section className="offering-mobile-story offering-shell"><div><p className="cine-eyebrow">Reachable beyond the desk</p><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p><StepCards d={d}/></div><ProductComposition kind="mobile" photo="hospitality" context="feature"/></section><section className="offering-mobile-context offering-shell"><p className="cine-eyebrow">Built around the people who move</p><div><article><Building2/><h3>Across the property</h3><p>Connect hotel managers, room service and maintenance as they respond to guests.</p></article><article><Users/><h3>Across the campus</h3><p>Help colleagues reach teams who are moving between buildings and facilities.</p></article><article><Radio/><h3>Across the field</h3><p>Keep mobile staff connected to their enterprise communications.</p></article></div></section></>
 return <section className={`offering-chapter offering-shell offering-chapter--${d.mode}`}><div className="offering-heading"><div><p className="cine-eyebrow">{item.slug==='ava'?'Assistance with a human handoff':item.slug==='analytics'?'Insight for everyday decisions':'A continuous quality practice'}</p><h2><Lines text={d.chapter}/></h2></div><p>{d.introduction}</p></div><DetailSignal kind={d.mode as 'voice'|'review'|'insight'} steps={d.steps}/>{item.slug==='ava'?<div className="offering-editorial-note"><h3>Start with a service task.</h3><p>Define the request, the information available and when a person should take over. Confirm the available capability and scope with the Tadiran team.</p></div>:item.slug==='recording-quality'?<div className="offering-review-loop"><span>Capture</span><ArrowRight/><span>Evaluate</span><ArrowRight/><span>Coach</span><ArrowRight/><span>Improve</span></div>:<div className="offering-insight-questions"><article><small>Service</small><h3>Where does demand build?</h3></article><article><small>Quality</small><h3>What should we learn from?</h3></article><article><small>People</small><h3>What will help the next shift?</h3></article></div>}</section>
}

function SolutionStory({item,d}:{item:Solution;d:DetailDirection}){
 if(d.mode==='deployment')return <><section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><div className="offering-integration-map"><div><span>CRM</span><span>Property systems</span><span>Operational systems</span></div><div className="offering-integration-map__hub"><Layers/><h3>Connected communications</h3><p>Map context, events and handoffs.</p></div><div><span>Your teams</span><span>Your customers</span><span>Your sites</span></div></div></section><section className="offering-deployment-section"><div className="offering-shell"><p className="cine-eyebrow">Explore your deployment path</p><h2>Three approaches.<br/>Your starting point.</h2><DeploymentExplorer/></div></section><section className="offering-shell offering-chapter"><h2>Make the transition together.</h2><StepCards d={d}/><div className="offering-editorial-note"><h3>Hospitality, connected.</h3><p>SmartHotel brings communications, guest services and hotel system integration together. Connect with hotel management systems including Oracle OPERA and OPTIMA.</p><Link className="offering-link" href="/industries/hospitality">Explore hospitality <ArrowRight size={18}/></Link></div></section></>
 if(d.mode==='channels')return <><section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><Channels/><StepCards d={d}/></section><section className="offering-cx-workspace"><div className="offering-shell"><div className="offering-heading"><div><p className="cine-eyebrow">The experience behind the service</p><h2>Give your team<br/>the whole conversation.</h2></div><p>One working environment for channels, customer information and assistance.</p></div><ProductComposition kind="workspace" photo="home-cx" context="feature"/><Link className="offering-link" href="/products/omnicx">Meet OmniCX <ArrowRight size={18}/></Link></div></section></>
 if(d.mode==='resilience')return <section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><div className="offering-resilience">{d.steps.map(([t,b],i)=>{const Icon=[Server,ShieldCheck,Radio][i];return <article key={t}><Icon size={32}/><small>0{i+1}</small><h3>{t}</h3><p>{b}</p><span>{['Dependencies → Availability','Identity → Access','Response → Recovery'][i]}</span></article>})}</div><div className="offering-editorial-note"><h3>Start with the operation that must continue.</h3><p>Bring IT, operations and support owners into one conversation. Establish what matters, who responds and how recovery will be reviewed.</p></div></section>
 if(d.mode==='cloud')return <section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><div className="offering-cloud-stack">{d.steps.map(([t,b],i)=><article key={t}><small>0{i+1}</small><div><h3>{t}</h3><p>{b}</p></div><span>{['Sites + users','Connectivity + ownership','New locations + hybrid'][i]}</span></article>)}</div><Link className="offering-link" href="/solutions/integrations-deployment">Compare cloud, hybrid and on-premises approaches <ArrowRight size={18}/></Link></section>
 if(d.mode==='oem')return <section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><div className="offering-oem-blueprint"><div className="offering-oem-blueprint__core"><Layers size={45}/><h3>Your product experience</h3><p>Communications, integrated.</p></div><ol>{d.steps.map(([t,b],i)=><li key={t}><small>0{i+1}</small><h3>{t}</h3><p>{b}</p></li>)}</ol></div><Link className="offering-link" href="/partners/apply?type=Software%20Developer%20%2F%20OEM">Explore an OEM partnership <ArrowRight size={18}/></Link></section>
 if(d.mode==='mso')return <section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><div className="offering-market"><div><strong>You know<br/>your customers.</strong><p>Market knowledge. Local relationships. A trusted point of contact.</p></div><div><strong>We bring<br/>the technology.</strong><p>Communications. Customer experience. Regional expertise.</p></div></div><StepCards d={d}/><Link className="offering-link" href="/partners">Meet the partner program <ArrowRight size={18}/></Link></section>
 if(d.mode==='insight')return <section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><div className="offering-intelligence"><Link href="/products/ava"><span>01 / In the moment</span><h3>Assist the person<br/>doing the work.</h3><p>Explore voice assistance and supported handoffs.</p><ArrowRight/></Link><Link href="/products/analytics"><span>02 / Across the operation</span><h3>See the patterns<br/>behind the work.</h3><p>Connect reporting, quality and operational insight.</p><ArrowRight/></Link></div><StepCards d={d}/></section>
 return <><section className="offering-chapter offering-shell"><div className="offering-heading"><h2><Lines text={d.chapter}/></h2><p>{d.introduction}</p></div><DetailSignal kind="network" steps={d.steps}/></section>{item.slug==='critical-communications'?<section className="offering-critical-sectors offering-shell"><p className="cine-eyebrow">Where coordination matters</p><div>{[['transportation','Transportation'],['power-utilities','Power & utilities'],['healthcare','Healthcare']].map(([slug,title])=><Link href={`/industries/${slug}`} key={slug}><Photo slug={slug}/><h3>{title}<ArrowRight size={20}/></h3></Link>)}</div></section>:<section className="offering-enterprise-tools offering-shell"><div><p className="cine-eyebrow">Your communications foundation</p><h2>One platform.<br/>Everyday connection.</h2><p>Aeonix connects voice, video, mobility and operational communications.</p><Link className="offering-link" href="/products/aeonix">Explore Aeonix <ArrowRight size={18}/></Link></div><ProductComposition kind="phone" photo="aeonix" context="feature"/></section>}</>
}

export function OfferingDetail({item}:{item:Product|Solution}){
 const product=item.kind==='product',collection=product?'products':'solutions'
 const d=(product?productDirections:solutionDirections)[item.slug]
 const device=product&&['omnicx','aeonix','mobile-touch'].includes(item.slug)
 const heroPhoto=item.slug==='omnicx'?'home-cx':item.slug
 const related=product?item.related:item.products
 return <OfferingMotion className={`page offering-page offering-page--${item.slug} offering-page--${d.layout} relationship-page`}>
  <nav className="offering-shell offering-breadcrumb" aria-label="Breadcrumb"><Link href={`/${collection}`}>{product?'Products':'Solutions'}</Link><span>/</span><span aria-current="page">{item.title}</span></nav>
  <section className={`offering-hero offering-hero--${d.layout} offering-shell`}>
   <div className="offering-hero__copy" data-arrive><p className="cine-eyebrow">{item.title}</p><h1><Lines text={d.title}/></h1><p>{d.lead}</p><div className="offering-hero__actions"><Link className="action" href={`/contact?interest=${encodeURIComponent(item.title)}`}>{product?'Let’s talk about '+(item.slug==='omnicx'?'OmniCX':item.slug==='aeonix'?'Aeonix':'your team'):'Talk to a specialist'}<ArrowRight size={17}/></Link><a className="offering-link" href="#in-action">Explore {product?'the product':'the solution'} ↓</a></div></div>
   {device?<ProductComposition kind={item.slug==='omnicx'?'workspace':item.slug==='aeonix'?'phone':'mobile'} photo={heroPhoto}/>:<div className="offering-hero__visual"><Photo slug={heroPhoto}/><Caption>{item.eyebrow}</Caption></div>}
  </section>
  <nav className="offering-section-nav offering-shell" aria-label="On this page"><a href="#in-action">{product?'In action':'Your operation'}</a><a href="#capabilities">{product?'Capabilities':'Plan your approach'}</a><a href="#next-step">{product?'Connected products':'Explore the technology'}</a></nav>
  <div id="in-action">{product?<ProductStory item={item} d={d}/>:<SolutionStory item={item} d={d}/>}</div>
  <section id="capabilities" className={`offering-capabilities ${product?'':'offering-capabilities--solution'}`}><div className="offering-shell">{product?<><div className="offering-heading"><div><p className="cine-eyebrow">Designed for your team</p><h2>{item.slug==='omnicx'?'Make service flow.':item.slug==='aeonix'?'Built for the way you connect.':item.slug==='ava'?'Assistance, with intention.':item.slug==='analytics'?'Questions worth answering.':item.slug==='recording-quality'?'A considered quality workflow.':'Keep work within reach.'}</h2></div><p>{item.audience}</p></div><div className="offering-capability-grid" data-stagger>{productFeatures[item.slug].map((c,i)=><article key={c.title}><small>0{i+1}</small><h3>{c.title}</h3><p>{c.body}</p></article>)}</div></>:<><p className="cine-eyebrow">Plan around what matters</p><div className="offering-planning"><h2>{d.mode==='oem'||d.mode==='mso'?'A partnership built around your business.':d.mode==='deployment'?'The right model starts with your requirements.':'From the first conversation to a considered plan.'}</h2><div><p>{d.mode==='oem'||d.mode==='mso'?'Bring your offering, customer needs and delivery model. Work with our partner team to define the scope and the responsibilities.':d.mode==='cloud'?'Start with your sites, users and connectivity. Agree service ownership and the transition path before moving forward.':'Start with the workflows, people and systems you need to connect. Map the requirements with a Tadiran specialist.'}</p><ul>{item.workflows.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></div></div></>}</div></section>
  <section id="next-step" className="offering-next offering-shell"><div className="offering-heading"><div><p className="cine-eyebrow">Keep exploring</p><h2>{product?'Part of a connected portfolio.':'The technology behind the solution.'}</h2></div>{product&&<p>{item.deployment}</p>}</div><div className="offering-related">{related.map(href=><Link key={href} href={href}>{findByHref(href)?.title||(href.endsWith('apply')?'Become a partner':'Partner program')}<ArrowRight size={19}/></Link>)}</div></section>
  <section className="relationship-closing"><p className="cine-eyebrow">Simply done right.</p><h2>{d.closing}</h2><Link className="action" href={`/contact?interest=${encodeURIComponent(item.title)}`}>Start a conversation <ArrowRight size={18}/></Link></section>
 </OfferingMotion>
}


