'use client'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useRef, useState } from 'react'
import { brandFacts } from '@/content/brand-story'

const solutions = [
 ['Enterprise communications','Connect offices, mobile teams and control rooms.','enterprise-communications'],
 ['Customer experience','Bring channels and customer context together.','omnichannel-cx'],
 ['AI & analytics','Support service teams with assistance and insights.','ai-analytics'],
 ['Critical communications','Keep people connected in demanding environments.','critical-communications'],
]
const industries = [['Healthcare','Support the people delivering care.','healthcare'],['Hospitality','Make every welcome feel connected.','hospitality'],['Transportation','Keep teams and operations moving.','transportation']]
function CTA({href,children}:{href:string;children:React.ReactNode}){return <Link className="wc-button" href={href}>{children}<span aria-hidden="true">↗</span></Link>}
export function WarmHome(){
 const story=useRef<HTMLElement>(null)
 const [active,setActive]=useState(0)
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.chapter))}),{rootMargin:'-35% 0px -35% 0px'});story.current?.querySelectorAll('[data-chapter]').forEach(e=>observer.observe(e));return()=>observer.disconnect()},[])
 return <div className="wc-home">
 <section className="wc-hero wc-wrap"><div className="wc-hero-copy"><p className="wc-kicker">Enterprise technology. Human connection.</p><h1>Bring people closer.<br/><span>Keep business<br/>moving.</span></h1><p className="wc-lead">Connect your teams, customer conversations and critical operations with communications built around your business.</p><div className="wc-actions"><CTA href="/solutions">Explore Solutions</CTA><Link className="wc-link" href="/contact">Talk to an Expert ↗</Link></div><a className="wc-scroll" href="#connections">Discover what connects us ↓</a></div><div className="wc-hero-photo"><Image src="/media/home/sol-cx-v4.webp" alt="Colleagues working together in a bright customer service workspace" fill priority sizes="(max-width:800px) 100vw,48vw"/><div className="wc-photo-note"><span className="wc-dot"/><div><small>Simply done right.</small><p>Better connections.<br/>More human experiences.</p></div></div></div></section>
 <section className="wc-proof wc-wrap" aria-label="Tadiran at a glance"><div><p className="wc-kicker">Experience you can build on</p><Link href="/about">Get to know Tadiran ↗</Link></div>{brandFacts.map(f=><div className="wc-fact" key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}<p className="wc-source">Company profile · September 2026</p></section>
 <section className="wc-intro wc-wrap" id="connections"><p className="wc-kicker">Technology connects. People make it matter.</p><div className="wc-heading"><h2>Closer to your customers.<br/><span>Connected across your business.</span></h2><p>From the first customer conversation to the call that keeps an operation moving. Bring people, channels and business systems together.</p></div><a className="wc-scroll" href="#solutions">Skip to solutions ↓</a></section>
 <section className="wc-story wc-wrap" ref={story} aria-label="Connected conversations and operations"><div className="wc-chapters"><article data-chapter="0"><p className="wc-kicker">01 / A better conversation</p><h2>Every channel.<br/><span>One shared context.</span></h2><p>Give your team a clearer view of the customer. OmniCX brings voice, digital channels and customer information into one working environment.</p><ul><li>Voice and digital conversations</li><li>Routing and automation</li><li>Customer context and reporting</li></ul><Link className="wc-link" href="/products/omnicx">Discover OmniCX ↗</Link><Image className="wc-mobile-product" src="/brand/reference-assets/omnicx-workspace.webp" alt="OmniCX conversation workspace" width={1500} height={844}/></article><article data-chapter="1"><p className="wc-kicker">02 / A connected organization</p><h2>Keep your people<br/><span>within reach.</span></h2><p>From the office to the field, Aeonix connects teams with enterprise communications built for continuity. Voice, video and mobility support the way your people work.</p><ul><li>Office and mobile teams</li><li>Control rooms and critical operations</li><li>Cloud, hybrid and on-premises options</li></ul><Link className="wc-link" href="/products/aeonix">Explore Aeonix ↗</Link><Image className="wc-mobile-product wc-mobile-phone" src="/brand/reference-assets/aeonix-mobile.webp" alt="Aeonix Touch mobile application" width={660} height={1200}/></article></div><div className="wc-stage" aria-hidden="true" data-active={active}><div className="wc-stage-top"><span>Tadiran / Connected by design</span><span>0{active+1} — 02</span></div><svg className="wc-connection" viewBox="0 0 600 600" fill="none"><path d="M-20 150C150 150 80 480 280 440S400 150 650 230" stroke="currentColor" strokeWidth="2" strokeDasharray="8 8"/></svg><div className={`wc-visual wc-visual-cx ${active===0?'is-active':''}`}><div className="wc-channels"><span>Voice</span><span>Chat</span><span>Email</span></div><Image src="/brand/reference-assets/omnicx-workspace.webp" alt="" width={1500} height={844}/><p>One workspace. Every conversation.</p></div><div className={`wc-visual wc-visual-aeonix ${active===1?'is-active':''}`}><Image src="/brand/reference-assets/aeonix-mobile.webp" alt="" width={660} height={1200}/><p>Your team. Connected wherever work happens.</p></div><span className="wc-stage-bottom">People. Conversations. Business.</span></div></section>
 <section className="wc-solutions wc-wrap" id="solutions"><div className="wc-heading"><div><p className="wc-kicker">Find your way forward</p><h2>What would you<br/>like to make possible?</h2></div><Link className="wc-link" href="/solutions">All solutions ↗</Link></div><div className="wc-solution-grid">{solutions.map(([title,body,slug],i)=><Link href={`/solutions/${slug}`} key={slug}><small>0{i+1}</small><h3>{title}</h3><p>{body}</p><span className="wc-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="wc-deployment"><div className="wc-wrap"><p className="wc-kicker">Modernize on your terms</p><div className="wc-heading"><h2>Your business.<br/>Your way forward.</h2><p>Build on what works today. Choose the deployment approach that fits your organization, your infrastructure and your next chapter.</p></div><div className="wc-deploy-grid">{[['Cloud','A service model for distributed organizations.'],['Hybrid','Connect existing and new environments as your needs evolve.'],['On premises','Maintain local control of your communications systems.']].map(([title,body],i)=><Link href="/solutions/integrations-deployment" key={title}><small>0{i+1}</small><h3>{title} <span aria-hidden="true">↗</span></h3><p>{body}</p></Link>)}</div></div></section>
 <section className="wc-industries wc-wrap"><div className="wc-heading"><div><p className="wc-kicker">Built around your world</p><h2>Different industries.<br/><span>A shared need to connect.</span></h2></div><Link className="wc-link" href="/industries">Explore industries ↗</Link></div><div className="wc-industry-grid">{industries.map(([title,body,slug])=><Link href={`/industries/${slug}`} key={slug}><div className="wc-industry-photo"><Image src={`/media/${slug}.webp`} alt={`${title} working environment`} fill sizes="(max-width:800px) 100vw,33vw"/></div><h3>{title}<span aria-hidden="true">↗</span></h3><p>{body}</p></Link>)}</div><p className="wc-other">Also connecting <Link href="/industries/power-utilities">Power & Utilities</Link><Link href="/industries/education">Education</Link><Link href="/industries/assisted-living">Assisted Living</Link></p></section>
 <section className="wc-partners wc-wrap"><div className="wc-partner-photo"><Image src="/media/partners.webp" alt="Business partners meeting in an office" fill sizes="(max-width:800px) 100vw,45vw"/></div><div><p className="wc-kicker">Global reach. Local understanding.</p><h2>Good technology.<br/><span>Great partnerships.</span></h2><p>Bring Tadiran technology to your market, backed by regional teams and a shared focus on your customers.</p><CTA href="/partners">Explore our partner program</CTA></div></section>
 <section className="wc-resources wc-wrap"><p className="wc-kicker">A clearer view of what’s next</p><h2>Explore the possibilities.</h2><div>{[['Customer experience','Get to know OmniCX','/products/omnicx'],['Enterprise communications','Meet Aeonix','/products/aeonix'],['Resources','Keep the conversation going','/resources']].map(([label,title,href])=><Link href={href} key={href}><small>{label}</small><h3>{title}</h3><span>Explore more ↗</span></Link>)}</div></section>
 <section className="wc-closing wc-wrap"><p className="wc-kicker">Let’s connect</p><h2>Your next chapter.<br/>Simply done right.</h2><div><p>Tell us what you want to connect.<br/>Let’s find the right way forward.</p><CTA href="/contact">Talk to an Expert</CTA></div></section>
 </div>
}
